/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.verovio.lib;

public final class fileFormat {
  public final static fileFormat UNKNOWN = new fileFormat("UNKNOWN", verovioJNI.UNKNOWN_get());
  public final static fileFormat AUTO = new fileFormat("AUTO");
  public final static fileFormat MEI = new fileFormat("MEI");
  public final static fileFormat HUMDRUM = new fileFormat("HUMDRUM");
  public final static fileFormat HUMMEI = new fileFormat("HUMMEI");
  public final static fileFormat HUMMIDI = new fileFormat("HUMMIDI");
  public final static fileFormat PAE = new fileFormat("PAE");
  public final static fileFormat ABC = new fileFormat("ABC");
  public final static fileFormat CMME = new fileFormat("CMME");
  public final static fileFormat DARMS = new fileFormat("DARMS");
  public final static fileFormat VOLPIANO = new fileFormat("VOLPIANO");
  public final static fileFormat MUSICXML = new fileFormat("MUSICXML");
  public final static fileFormat MUSICXMLHUM = new fileFormat("MUSICXMLHUM");
  public final static fileFormat MEIHUM = new fileFormat("MEIHUM");
  public final static fileFormat MUSEDATAHUM = new fileFormat("MUSEDATAHUM");
  public final static fileFormat ESAC = new fileFormat("ESAC");
  public final static fileFormat MIDI = new fileFormat("MIDI");
  public final static fileFormat TIMEMAP = new fileFormat("TIMEMAP");
  public final static fileFormat EXPANSIONMAP = new fileFormat("EXPANSIONMAP");
  public final static fileFormat SERIALIZATION = new fileFormat("SERIALIZATION");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static fileFormat swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + fileFormat.class + " with value " + swigValue);
  }

  private fileFormat(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private fileFormat(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private fileFormat(String swigName, fileFormat swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static fileFormat[] swigValues = { UNKNOWN, AUTO, MEI, HUMDRUM, HUMMEI, HUMMIDI, PAE, ABC, CMME, DARMS, VOLPIANO, MUSICXML, MUSICXMLHUM, MEIHUM, MUSEDATAHUM, ESAC, MIDI, TIMEMAP, EXPANSIONMAP, SERIALIZATION };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

