/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.verovio.lib;

public class toolkit {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected toolkit(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(toolkit obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(toolkit obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        verovioJNI.delete_toolkit(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public toolkit(boolean initFont) {
    this(verovioJNI.new_toolkit__SWIG_0(initFont), true);
  }

  public toolkit() {
    this(verovioJNI.new_toolkit__SWIG_1(), true);
  }

  public String getID() {
    return verovioJNI.toolkit_getID(swigCPtr, this);
  }

  public String getResourcePath() {
    return verovioJNI.toolkit_getResourcePath(swigCPtr, this);
  }

  public boolean setResourcePath(String path) {
    return verovioJNI.toolkit_setResourcePath(swigCPtr, this, path);
  }

  public String getLog() {
    return verovioJNI.toolkit_getLog(swigCPtr, this);
  }

  public String getVersion() {
    return verovioJNI.toolkit_getVersion(swigCPtr, this);
  }

  public void resetXmlIdSeed(int seed) {
    verovioJNI.toolkit_resetXmlIdSeed(swigCPtr, this, seed);
  }

  public boolean loadFile(String filename) {
    return verovioJNI.toolkit_loadFile(swigCPtr, this, filename);
  }

  public boolean loadData(String data) {
    return verovioJNI.toolkit_loadData(swigCPtr, this, data);
  }

  public boolean loadZipDataBase64(String data) {
    return verovioJNI.toolkit_loadZipDataBase64(swigCPtr, this, data);
  }

  public boolean loadZipDataBuffer(SWIGTYPE_p_unsigned_char data, int length) {
    return verovioJNI.toolkit_loadZipDataBuffer(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(data), length);
  }

  public String validatePAEFile(String filename) {
    return verovioJNI.toolkit_validatePAEFile(swigCPtr, this, filename);
  }

  public String validatePAE(String data) {
    return verovioJNI.toolkit_validatePAE(swigCPtr, this, data);
  }

  public int getPageCount() {
    return verovioJNI.toolkit_getPageCount(swigCPtr, this);
  }

  public String getOptions() {
    return verovioJNI.toolkit_getOptions(swigCPtr, this);
  }

  public String getDefaultOptions() {
    return verovioJNI.toolkit_getDefaultOptions(swigCPtr, this);
  }

  public String getAvailableOptions() {
    return verovioJNI.toolkit_getAvailableOptions(swigCPtr, this);
  }

  public boolean setOptions(String jsonOptions) {
    return verovioJNI.toolkit_setOptions(swigCPtr, this, jsonOptions);
  }

  public void resetOptions() {
    verovioJNI.toolkit_resetOptions(swigCPtr, this);
  }

  public void printOptionUsage(String category, SWIGTYPE_p_std__ostream output) {
    verovioJNI.toolkit_printOptionUsage(swigCPtr, this, category, SWIGTYPE_p_std__ostream.getCPtr(output));
  }

  public String getOptionUsageString() {
    return verovioJNI.toolkit_getOptionUsageString(swigCPtr, this);
  }

  public boolean setScale(int scale) {
    return verovioJNI.toolkit_setScale(swigCPtr, this, scale);
  }

  public int getScale() {
    return verovioJNI.toolkit_getScale(swigCPtr, this);
  }

  public boolean setInputFrom(String inputFrom) {
    return verovioJNI.toolkit_setInputFrom(swigCPtr, this, inputFrom);
  }

  public boolean setOutputTo(String outputTo) {
    return verovioJNI.toolkit_setOutputTo(swigCPtr, this, outputTo);
  }

  public boolean select(String selection) {
    return verovioJNI.toolkit_select(swigCPtr, this, selection);
  }

  public boolean edit(String editorAction) {
    return verovioJNI.toolkit_edit(swigCPtr, this, editorAction);
  }

  public String editInfo() {
    return verovioJNI.toolkit_editInfo(swigCPtr, this);
  }

  public String renderData(String data, String jsonOptions) {
    return verovioJNI.toolkit_renderData(swigCPtr, this, data, jsonOptions);
  }

  public String renderToSVG(int pageNo, boolean xmlDeclaration) {
    return verovioJNI.toolkit_renderToSVG__SWIG_0(swigCPtr, this, pageNo, xmlDeclaration);
  }

  public String renderToSVG(int pageNo) {
    return verovioJNI.toolkit_renderToSVG__SWIG_1(swigCPtr, this, pageNo);
  }

  public String renderToSVG() {
    return verovioJNI.toolkit_renderToSVG__SWIG_2(swigCPtr, this);
  }

  public boolean renderToSVGFile(String filename, int pageNo) {
    return verovioJNI.toolkit_renderToSVGFile__SWIG_0(swigCPtr, this, filename, pageNo);
  }

  public boolean renderToSVGFile(String filename) {
    return verovioJNI.toolkit_renderToSVGFile__SWIG_1(swigCPtr, this, filename);
  }

  public String renderToMIDI() {
    return verovioJNI.toolkit_renderToMIDI(swigCPtr, this);
  }

  public boolean renderToMIDIFile(String filename) {
    return verovioJNI.toolkit_renderToMIDIFile(swigCPtr, this, filename);
  }

  public String renderToPAE() {
    return verovioJNI.toolkit_renderToPAE(swigCPtr, this);
  }

  public boolean renderToPAEFile(String filename) {
    return verovioJNI.toolkit_renderToPAEFile(swigCPtr, this, filename);
  }

  public String renderToTimemap(String jsonOptions) {
    return verovioJNI.toolkit_renderToTimemap__SWIG_0(swigCPtr, this, jsonOptions);
  }

  public String renderToTimemap() {
    return verovioJNI.toolkit_renderToTimemap__SWIG_1(swigCPtr, this);
  }

  public String renderToExpansionMap() {
    return verovioJNI.toolkit_renderToExpansionMap(swigCPtr, this);
  }

  public boolean renderToTimemapFile(String filename, String jsonOptions) {
    return verovioJNI.toolkit_renderToTimemapFile__SWIG_0(swigCPtr, this, filename, jsonOptions);
  }

  public boolean renderToTimemapFile(String filename) {
    return verovioJNI.toolkit_renderToTimemapFile__SWIG_1(swigCPtr, this, filename);
  }

  public boolean renderToExpansionMapFile(String filename) {
    return verovioJNI.toolkit_renderToExpansionMapFile(swigCPtr, this, filename);
  }

  public String getHumdrum() {
    return verovioJNI.toolkit_getHumdrum__SWIG_0(swigCPtr, this);
  }

  public String convertMEIToHumdrum(String meiData) {
    return verovioJNI.toolkit_convertMEIToHumdrum(swigCPtr, this, meiData);
  }

  public String convertHumdrumToHumdrum(String humdrumData) {
    return verovioJNI.toolkit_convertHumdrumToHumdrum(swigCPtr, this, humdrumData);
  }

  public String convertHumdrumToMIDI(String humdrumData) {
    return verovioJNI.toolkit_convertHumdrumToMIDI(swigCPtr, this, humdrumData);
  }

  public boolean getHumdrumFile(String filename) {
    return verovioJNI.toolkit_getHumdrumFile(swigCPtr, this, filename);
  }

  public String getMEI(String jsonOptions) {
    return verovioJNI.toolkit_getMEI__SWIG_0(swigCPtr, this, jsonOptions);
  }

  public String getMEI() {
    return verovioJNI.toolkit_getMEI__SWIG_1(swigCPtr, this);
  }

  public boolean saveFile(String filename, String jsonOptions) {
    return verovioJNI.toolkit_saveFile__SWIG_0(swigCPtr, this, filename, jsonOptions);
  }

  public boolean saveFile(String filename) {
    return verovioJNI.toolkit_saveFile__SWIG_1(swigCPtr, this, filename);
  }

  public String getDescriptiveFeatures(String jsonOptions) {
    return verovioJNI.toolkit_getDescriptiveFeatures(swigCPtr, this, jsonOptions);
  }

  public String getElementsAtTime(int millisec) {
    return verovioJNI.toolkit_getElementsAtTime(swigCPtr, this, millisec);
  }

  public int getPageWithElement(String xmlId) {
    return verovioJNI.toolkit_getPageWithElement(swigCPtr, this, xmlId);
  }

  public String getElementAttr(String xmlId) {
    return verovioJNI.toolkit_getElementAttr(swigCPtr, this, xmlId);
  }

  public String getNotatedIdForElement(String xmlId) {
    return verovioJNI.toolkit_getNotatedIdForElement(swigCPtr, this, xmlId);
  }

  public String getExpansionIdsForElement(String xmlId) {
    return verovioJNI.toolkit_getExpansionIdsForElement(swigCPtr, this, xmlId);
  }

  public int getTimeForElement(String xmlId) {
    return verovioJNI.toolkit_getTimeForElement(swigCPtr, this, xmlId);
  }

  public String getMIDIValuesForElement(String xmlId) {
    return verovioJNI.toolkit_getMIDIValuesForElement(swigCPtr, this, xmlId);
  }

  public String getTimesForElement(String xmlId) {
    return verovioJNI.toolkit_getTimesForElement(swigCPtr, this, xmlId);
  }

  public void redoLayout(String jsonOptions) {
    verovioJNI.toolkit_redoLayout__SWIG_0(swigCPtr, this, jsonOptions);
  }

  public void redoLayout() {
    verovioJNI.toolkit_redoLayout__SWIG_1(swigCPtr, this);
  }

  public void redoPagePitchPosLayout() {
    verovioJNI.toolkit_redoPagePitchPosLayout(swigCPtr, this);
  }

  public boolean renderToDeviceContext(int pageNo, SWIGTYPE_p_DeviceContext deviceContext) {
    return verovioJNI.toolkit_renderToDeviceContext(swigCPtr, this, pageNo, SWIGTYPE_p_DeviceContext.getCPtr(deviceContext));
  }

  public SWIGTYPE_p_Options getOptionsObj() {
    long cPtr = verovioJNI.toolkit_getOptionsObj(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Options(cPtr, false);
  }

  public void getHumdrum(SWIGTYPE_p_std__ostream output) {
    verovioJNI.toolkit_getHumdrum__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(output));
  }

  public void setHumdrumBuffer(String contents) {
    verovioJNI.toolkit_setHumdrumBuffer(swigCPtr, this, contents);
  }

  public String getHumdrumBuffer() {
    return verovioJNI.toolkit_getHumdrumBuffer(swigCPtr, this);
  }

  public void clearHumdrumBuffer() {
    verovioJNI.toolkit_clearHumdrumBuffer(swigCPtr, this);
  }

  public SWIGTYPE_p_FileFormat getInputFrom() {
    return new SWIGTYPE_p_FileFormat(verovioJNI.toolkit_getInputFrom(swigCPtr, this), true);
  }

  public SWIGTYPE_p_FileFormat getOutputTo() {
    return new SWIGTYPE_p_FileFormat(verovioJNI.toolkit_getOutputTo(swigCPtr, this), true);
  }

  public void setLocale() {
    verovioJNI.toolkit_setLocale(swigCPtr, this);
  }

  public void resetLocale() {
    verovioJNI.toolkit_resetLocale(swigCPtr, this);
  }

  public void initClock() {
    verovioJNI.toolkit_initClock(swigCPtr, this);
  }

  public void resetClock() {
    verovioJNI.toolkit_resetClock(swigCPtr, this);
  }

  public double getRuntimeInSeconds() {
    return verovioJNI.toolkit_getRuntimeInSeconds(swigCPtr, this);
  }

  public void logRuntime() {
    verovioJNI.toolkit_logRuntime(swigCPtr, this);
  }

}
