/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.verovio.lib;

public class verovioJNI {
  public final static native long new_toolkit__SWIG_0(boolean jarg1);
  public final static native long new_toolkit__SWIG_1();
  public final static native void delete_toolkit(long jarg1);
  public final static native String toolkit_getID(long jarg1, toolkit jarg1_);
  public final static native String toolkit_getResourcePath(long jarg1, toolkit jarg1_);
  public final static native boolean toolkit_setResourcePath(long jarg1, toolkit jarg1_, String jarg2);
  public final static native String toolkit_getLog(long jarg1, toolkit jarg1_);
  public final static native String toolkit_getVersion(long jarg1, toolkit jarg1_);
  public final static native void toolkit_resetXmlIdSeed(long jarg1, toolkit jarg1_, int jarg2);
  public final static native boolean toolkit_loadFile(long jarg1, toolkit jarg1_, String jarg2);
  public final static native boolean toolkit_loadData(long jarg1, toolkit jarg1_, String jarg2);
  public final static native boolean toolkit_loadZipDataBase64(long jarg1, toolkit jarg1_, String jarg2);
  public final static native boolean toolkit_loadZipDataBuffer(long jarg1, toolkit jarg1_, long jarg2, int jarg3);
  public final static native String toolkit_validatePAEFile(long jarg1, toolkit jarg1_, String jarg2);
  public final static native String toolkit_validatePAE(long jarg1, toolkit jarg1_, String jarg2);
  public final static native int toolkit_getPageCount(long jarg1, toolkit jarg1_);
  public final static native String toolkit_getOptions(long jarg1, toolkit jarg1_);
  public final static native String toolkit_getDefaultOptions(long jarg1, toolkit jarg1_);
  public final static native String toolkit_getAvailableOptions(long jarg1, toolkit jarg1_);
  public final static native boolean toolkit_setOptions(long jarg1, toolkit jarg1_, String jarg2);
  public final static native void toolkit_resetOptions(long jarg1, toolkit jarg1_);
  public final static native void toolkit_printOptionUsage(long jarg1, toolkit jarg1_, String jarg2, long jarg3);
  public final static native String toolkit_getOptionUsageString(long jarg1, toolkit jarg1_);
  public final static native boolean toolkit_setScale(long jarg1, toolkit jarg1_, int jarg2);
  public final static native int toolkit_getScale(long jarg1, toolkit jarg1_);
  public final static native boolean toolkit_setInputFrom(long jarg1, toolkit jarg1_, String jarg2);
  public final static native boolean toolkit_setOutputTo(long jarg1, toolkit jarg1_, String jarg2);
  public final static native boolean toolkit_select(long jarg1, toolkit jarg1_, String jarg2);
  public final static native boolean toolkit_edit(long jarg1, toolkit jarg1_, String jarg2);
  public final static native String toolkit_editInfo(long jarg1, toolkit jarg1_);
  public final static native String toolkit_renderData(long jarg1, toolkit jarg1_, String jarg2, String jarg3);
  public final static native String toolkit_renderToSVG__SWIG_0(long jarg1, toolkit jarg1_, int jarg2, boolean jarg3);
  public final static native String toolkit_renderToSVG__SWIG_1(long jarg1, toolkit jarg1_, int jarg2);
  public final static native String toolkit_renderToSVG__SWIG_2(long jarg1, toolkit jarg1_);
  public final static native boolean toolkit_renderToSVGFile__SWIG_0(long jarg1, toolkit jarg1_, String jarg2, int jarg3);
  public final static native boolean toolkit_renderToSVGFile__SWIG_1(long jarg1, toolkit jarg1_, String jarg2);
  public final static native String toolkit_renderToMIDI(long jarg1, toolkit jarg1_);
  public final static native boolean toolkit_renderToMIDIFile(long jarg1, toolkit jarg1_, String jarg2);
  public final static native String toolkit_renderToPAE(long jarg1, toolkit jarg1_);
  public final static native boolean toolkit_renderToPAEFile(long jarg1, toolkit jarg1_, String jarg2);
  public final static native String toolkit_renderToTimemap__SWIG_0(long jarg1, toolkit jarg1_, String jarg2);
  public final static native String toolkit_renderToTimemap__SWIG_1(long jarg1, toolkit jarg1_);
  public final static native String toolkit_renderToExpansionMap(long jarg1, toolkit jarg1_);
  public final static native boolean toolkit_renderToTimemapFile__SWIG_0(long jarg1, toolkit jarg1_, String jarg2, String jarg3);
  public final static native boolean toolkit_renderToTimemapFile__SWIG_1(long jarg1, toolkit jarg1_, String jarg2);
  public final static native boolean toolkit_renderToExpansionMapFile(long jarg1, toolkit jarg1_, String jarg2);
  public final static native String toolkit_getHumdrum__SWIG_0(long jarg1, toolkit jarg1_);
  public final static native String toolkit_convertMEIToHumdrum(long jarg1, toolkit jarg1_, String jarg2);
  public final static native String toolkit_convertHumdrumToHumdrum(long jarg1, toolkit jarg1_, String jarg2);
  public final static native String toolkit_convertHumdrumToMIDI(long jarg1, toolkit jarg1_, String jarg2);
  public final static native boolean toolkit_getHumdrumFile(long jarg1, toolkit jarg1_, String jarg2);
  public final static native String toolkit_getMEI__SWIG_0(long jarg1, toolkit jarg1_, String jarg2);
  public final static native String toolkit_getMEI__SWIG_1(long jarg1, toolkit jarg1_);
  public final static native boolean toolkit_saveFile__SWIG_0(long jarg1, toolkit jarg1_, String jarg2, String jarg3);
  public final static native boolean toolkit_saveFile__SWIG_1(long jarg1, toolkit jarg1_, String jarg2);
  public final static native String toolkit_getDescriptiveFeatures(long jarg1, toolkit jarg1_, String jarg2);
  public final static native String toolkit_getElementsAtTime(long jarg1, toolkit jarg1_, int jarg2);
  public final static native int toolkit_getPageWithElement(long jarg1, toolkit jarg1_, String jarg2);
  public final static native String toolkit_getElementAttr(long jarg1, toolkit jarg1_, String jarg2);
  public final static native String toolkit_getNotatedIdForElement(long jarg1, toolkit jarg1_, String jarg2);
  public final static native String toolkit_getExpansionIdsForElement(long jarg1, toolkit jarg1_, String jarg2);
  public final static native int toolkit_getTimeForElement(long jarg1, toolkit jarg1_, String jarg2);
  public final static native String toolkit_getMIDIValuesForElement(long jarg1, toolkit jarg1_, String jarg2);
  public final static native String toolkit_getTimesForElement(long jarg1, toolkit jarg1_, String jarg2);
  public final static native void toolkit_redoLayout__SWIG_0(long jarg1, toolkit jarg1_, String jarg2);
  public final static native void toolkit_redoLayout__SWIG_1(long jarg1, toolkit jarg1_);
  public final static native void toolkit_redoPagePitchPosLayout(long jarg1, toolkit jarg1_);
  public final static native boolean toolkit_renderToDeviceContext(long jarg1, toolkit jarg1_, int jarg2, long jarg3);
  public final static native long toolkit_getOptionsObj(long jarg1, toolkit jarg1_);
  public final static native void toolkit_getHumdrum__SWIG_1(long jarg1, toolkit jarg1_, long jarg2);
  public final static native void toolkit_setHumdrumBuffer(long jarg1, toolkit jarg1_, String jarg2);
  public final static native String toolkit_getHumdrumBuffer(long jarg1, toolkit jarg1_);
  public final static native void toolkit_clearHumdrumBuffer(long jarg1, toolkit jarg1_);
  public final static native long toolkit_getInputFrom(long jarg1, toolkit jarg1_);
  public final static native long toolkit_getOutputTo(long jarg1, toolkit jarg1_);
  public final static native void toolkit_setLocale(long jarg1, toolkit jarg1_);
  public final static native void toolkit_resetLocale(long jarg1, toolkit jarg1_);
  public final static native void toolkit_initClock(long jarg1, toolkit jarg1_);
  public final static native void toolkit_resetClock(long jarg1, toolkit jarg1_);
  public final static native double toolkit_getRuntimeInSeconds(long jarg1, toolkit jarg1_);
  public final static native void toolkit_logRuntime(long jarg1, toolkit jarg1_);
  public final static native int UNKNOWN_get();
  public final static native int LOG_OFF_get();
  public final static native int LOG_ERROR_get();
  public final static native int LOG_WARNING_get();
  public final static native int LOG_INFO_get();
  public final static native int LOG_DEBUG_get();
  public final static native void setDefaultResourcePath(String jarg1);
  public final static native void enableLog(int jarg1);
  public final static native void enableLogToBuffer(boolean jarg1);
}
