/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.verovio.lib;

public class verovio implements verovioConstants {
  public static void setDefaultResourcePath(String path) {
    verovioJNI.setDefaultResourcePath(path);
  }

  public static void enableLog(int level) {
    verovioJNI.enableLog(level);
  }

  public static void enableLogToBuffer(boolean value) {
    verovioJNI.enableLogToBuffer(value);
  }

}
