/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.verovio.lib;

public interface verovioConstants {
  public final static int LOG_OFF = verovioJNI.LOG_OFF_get();
  public final static int LOG_ERROR = verovioJNI.LOG_ERROR_get();
  public final static int LOG_WARNING = verovioJNI.LOG_WARNING_get();
  public final static int LOG_INFO = verovioJNI.LOG_INFO_get();
  public final static int LOG_DEBUG = verovioJNI.LOG_DEBUG_get();

}
